name: Deploy to S3

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        if: github.ref == 'refs/heads/staging'
        run: npm run build:staging

      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: npm run build:production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Deploy to staging S3
        if: github.ref == 'refs/heads/staging'
        run: aws s3 sync dist s3://staging-nationslab-lms --delete

      - name: Deploy to production S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync dist s3://nationslab-lms --delete 